---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temira-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mruggeri-temira.my.kube.um.edu.ar
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temira-service
                port:
                  number: 80

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: temira-config
data:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_PORT: "8501"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"

---
# Secret for SSH keys
apiVersion: v1
kind: Secret
metadata:
  name: ssh-keys
type: Opaque
data:
  clave_privada.pem:
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcWdJQkFBS0NBUUVBcjBkeFNhTkhF
    UStTY01UbURuZ3dmaW9MYW9PMEtoaEpOdGhLai9zUjV5U09UVDVsCnF3VDZRT3VsTTZlMnNnamRC
    RXVBeGNaTEJGS0owK2xZaUFxdC9oT2ZlWDh4Umx5ZksyWXpjMkEwQ0UvTnVGTnIKaHNVNkdEM0cv
    d1BRaENjY20rNTNod1g4eWltMklKWldjZnFoQnFSeExPQmJIOVNnRUNjblpoSUNEUTdvcVJGdQpD
    UTNyc2FYdFFsbCs0TzRqci82bzRucFhobjZrRDZ3d2ZlbkFQNjVibnkyQ2RjZUoydlJ5M2xjNVRG
    MWI3N0xvCjcxb1ZCU0h1Z1U3QjRBajllQVR3dHFsbEppU0dnNXJWY2FuMHowSzlhTTZ3SGdHcWJn
    Ti9kQUppSFJBL0lqSWoKNTJMUWdBalAzTWdZWU5WcVNNNkFnWkpnSkxyTzBuRDFoZnMzUHdJREFR
    QUJBb0lCQUJWdG1uL3lJaUlIMFZOUAovd0FOMlgvVERBbzloNjBOd3dXZGM2QWVoWlhJZGswakw3
    SzByUk42dTN1UktWaWlsTUtOcUhTRlJXNkYyS3U3CmYwTkNhdnNBMHlJN1ZuN1BtL1htVEt2eU91
    bzVOMkV0Y1p2TVNNbmw0NG9Sb1ZCR3A4eTRYb3gzUXV4RUpTdmUKdFRyQjlTV212TjlMbmxoSjJo
    d2dGVE92YytmRk9JNUI4ZjJwU2I4enR5WnE2YXhhampqL2gxbkwvZmlsdzFLNQpVczYrVnlsTkpT
    b0RKbFM3WVVuVW5Yc0VQcVVhSlpVYkU1S2JOcW1keG1BTk5kckFpNDM2UUI1RURHRVdrb2Z1CmxK
    VVBEZkF2UmdoUzhodytLK3ZCWUpwWURoZlZBN2xtSms1NFZTUG05MTJ5NUd4cHJuUEFrdXgwQy83
    WUlRQVQKbHFYNTFVRUNnWWtBNE92dnJvUklIV0czMnJTaUVOK3NTRVpqczc1ZVZTSGorY2ZaK1VX
    dHFlTUZROUZhMUNxUQozNXo1M1VRd3RxanNNNFFYMitGRWNXSzQwV01zSjZmWGY5Um5aQUZJdkNx
    UFl2bWNlbGtTd205eWo1U3ZlUmRMCmhkVzBCZGF3R1kxYktvRE1aMHVQWTFOR0xMMDdEZVk2bzBl
    VWwvejlDbkt5QzRJMnVXbGMzelFXZTJhTWlHSTMKYVFKNUFNZC9oUlVOcDJXcUVBSGliRnVuQjQ5
    YUJSZWZWNmcvRzJ6UVZxdVRzdzBLb3Nibld0bFdsZS94ZlIvSgpvb3IyYnN0clVsczNNVFpKMVBS
    aVorUWNpNzZzL002cHdMdDIwNnovYmk5RFpmYUtnVlFKdG13clROL0FJb05jCmZ3cTRmYWw3aVBp
    SjZlL2JObzRtMjMzOXJ2YlFHeFJyZnk0TVp3S0JpUURSMTIwakhXa0dlSCtHUFJZaXRmdE8KNXRU
    b0FnaVNWbThTUDRFK1RlS3E2QkdtWnZEZGx1VFlxdVIycWNMazk0NSt0Wk5vNGE3d05oR0YwSWVH
    YTlIagpBZkIvM2E3VlZzTzFySGx2c0NDUFpGaTJXaHFuMTdMdkp5U3dlYzZMMkZTZ3Y4OXo0NHZn
    Ti9YMWtZcEIrblRrCmxzaXNVQ3hvRGYvTU91MEJhS3ByMTNYT0pTdWhwamhaQW5oRDFqUGR0ZGZm
    TlJYZVhpejBlWGFUbzB1cC9hL2oKOFJtVlJiN0M5eVZpWU9SNitENm5PczhmV1NGd0JyTnp4MXBq
    WjJvSXhGckNtQmFHeDFPR2VNSjRJd0NRRVo4TQozOW9Zc0g2NktaUHBZcTJaY3ZnS0RpdEV4bU8y
    QVdUZHMyQmZtamM0TkVWTkgyQ01zOS9kRnI5QkJBREJUOUJlClN5OENnWWtBdmp3Nkl0REtSdTRV
    emtvb0dCeDMvUGxzTHpLM3l6UE9US1F0QVZGeG83anJsOFh5K0tWdnlVMlYKS2kwbkZhRFBDWkVT
    YkZCU0U0clVYTEVsNXJsWUEzZ3Q4a28zenAzRjVYQWVnNkVYRThRdGIyZVBQaEF5SW5iNQpzL1g0
    S3kxYk5sS3FBK3QzZ1M3eG9lK3dIU3gwNFRHd01FVnZ0VGZJaHZkT2pIVDBSRm9ENTErTW9xdEFS
    QT09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: temira-service
  labels:
    app: temira
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8501
  selector:
    app: temira

---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: temira
  labels:
    app: temira
spec:
  serviceName: "temira"
  replicas: 1
  selector:
    matchLabels:
      app: temira
  template:
    metadata:
      labels:
        app: temira
    spec:
      containers:
      - name: temira
        image: martinr2020/temira-web-analytics:latest
        ports:
        - containerPort: 8501

        env:
          - name: STREAMLIT_SERVER_HEADLESS
            valueFrom:
              configMapKeyRef:
                name: temira-config
                key: STREAMLIT_SERVER_HEADLESS

          - name: STREAMLIT_SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: temira-config
                key: STREAMLIT_SERVER_PORT

          - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
            valueFrom:
              configMapKeyRef:
                name: temira-config
                key: STREAMLIT_BROWSER_GATHER_USAGE_STATS

        volumeMounts:
        - name: ssh-keys-storage
          mountPath: /app/claves
          readOnly: true
        - name: temp-csvs-storage
          mountPath: /app/temp_csvs
        - name: temp-pdfs-storage
          mountPath: /app/temp_pdfs
        - name: temp-images-storage
          mountPath: /app/images

      volumes:
      - name: ssh-keys-storage
        secret:
          secretName: ssh-keys

  volumeClaimTemplates:
  - metadata:
      name: temp-csvs-storage
      labels:
        app: temira
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi

  - metadata:
      name: temp-pdfs-storage
      labels:
        app: temira
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi

  - metadata:
      name: temp-images-storage
      labels:
        app: temira
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
---

